tmp=float(input('Digite a duração da viagem:'))
vm=float(input('Digite a velocidade média:'))
dispe=(tmp*vm)
litg=(dispe/12)
print('Velocidade média:', vm)
print('Tempo gasto na viagem:',tmp)
print('Distância percorrida:', dispe)
print('Quantidade de litros usados:',litg)
